### ISSUE TITLE
Port to UNO/Other framework

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryCAD#269]
**Is your feature request related to a problem? Please describe.**
Many writers use Mac/Apple devices, however the app only runs on Windows 10/11 devices and as such apple users cannot run StoryBuilder, as such we should consider moving to another UI framework to make StoryBuilder more accessible.

**Describe the solution you'd like**
Port our code to UNO so we can run on Mac (and Linux ideally!)

MAUI may be an alternative.

**Comment by terrycox** [comment]
There's now a UNO textbook:
https://www.packtpub.com/product/creating-cross-platform-c-applications-with-uno-platform/9781801078498

**Comment by terrycox** [comment]
This has been moved to a Discussion topic, 'Port StoryBuilder to Cross-Platform Framework'.
