### ISSUE TITLE
Print all settings does not uncheck the setting (already selected)

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryCAD#327]
**Describe the bug**
Print all settings does not uncheck the setting (already selected)

1. Open the Glass Menagerie
2.  Click on settings (alley in St. Louis , Wingfield apt)
3. Select Reports
4. Check alley in St. Louis
5.  Then check Print All Setting
6. alley in St. Louis remains checked

Expected result:  unchecked alley in St. Louis and Wingfield apt and grayed out 
[updater.2022-05-25.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8775167/updater.2022-05-25.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/170386103-adee7fb6-dae1-4d96-ac99-72204a14dee5.png)

**Additional context**
this is what displays if I click print all first 
![image](https://user-images.githubusercontent.com/21226407/170386879-39e24dc9-70bf-47c6-9344-0f1ac7fdcc3b.png)

**Comment by Rarisma** [comment]
This is a visual bug and has no effect, but will be adressed.
