### ISSUE TITLE
Protagonist Conflict text box needs to be expanded to mirror other text boxes

### ISSUE THREAD

**Issue by henley352** [storybuilder-org/StoryCAD#348]
**Describe the bug**
Protagonist Conflict text box needs to be expanded to mirror other text boxes

**To Reproduce**
1. Go to 'New story...'
2. Click on 'Protagonist' tab
3. Scroll down to 'Conflict'
4. Text box mirrors others

**Expected behavior**
Text box mirrors others - see 2nd screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/21226407/173195096-59edc73f-a238-4fcc-b293-55e653df80ff.png)
![image](https://user-images.githubusercontent.com/21226407/173195206-d998ccac-dc42-41ae-b986-7ca025757db1.png)

**Additional context**
[updater.2022-06-11.log](https://github.com/storybuilder-org/StoryBuilder-2/files/8884266/updater.2022-06-11.log)

version 2.0.15.0

**Comment by terrycox** [comment]
CLosed per PR #570
