### ISSUE TITLE
Add auto-update to StoryBuilder

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryCAD#479]
**Is your feature request related to a problem? Please describe.**
Windows Store provides an ability for a Store app to be aware of any updates
and to download and install them. See the 'additional context' link below.

**Describe the solution you'd like**
Add update awareness to the app.

**Describe alternatives you've considered**
Leave things as they are

**Additional context**
https://learn.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates#mandatory-package-updates

**Comment by Rarisma** [comment]
This is not a feature in WinUI3 currently.

**Comment by terrycox** [comment]
Not needed; mandatory updates is a feature set on a release when it's distributed through the Store.
