### ISSUE TITLE
MarkdownSplitter emits invalid <br/> break closure tags for bulletpoints

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryCAD#487]
**Describe the bug**

**To Reproduce**
1.  Launch either test or production User Manual.
2. Click on QuickStart | The StoryBuilder User Interface.
3. Scroll down to 'The form's sections are as below'.
4. See error.

**Expected behavior**
The tags are removed.

**Screenshots**
<img width="776" alt="MarkdownSplitter break closure tags" src="https://user-images.githubusercontent.com/5607778/215996121-68e4a646-66c6-438f-bd42-c85d56b9d2cc.png">

**Additional context**
This might be fixed along with the Prev/Next navigation change.

**Comment by Rarisma** [comment]
Fixed
