### ISSUE TITLE
Relationships combobox appears to cut off

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryCAD#581]
**Describe the bug**
The relationships combobox appears to cut off.

**To Reproduce**
Open the relationships menu and click on the role.

**Expected behavior**
box doesnt cut off

**Screenshots**
![image](https://github.com/storybuilder-org/StoryCAD/assets/49795711/492c1c6d-aa99-4413-a2fb-07998b4c2143)

**Additional context**

**Comment by terrycox** [comment]
This is because NewRelationshipPage uses ComboBox instead of SfComboBox. This is a known issue with ComboBox, never fixed, and a problem waiting to happen. 
![NewRelationshipPage ComboBoxes](https://github.com/storybuilder-org/StoryCAD/assets/5607778/9f88bc40-84b5-44af-a716-30f3a731cfc5)

**Comment by Rarisma** [comment]
Fixed by #601
