### ISSUE TITLE
Key questions content dialog is initally empty, show a default

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryCAD#582]
**Is your feature request related to a problem? Please describe.**
The Key questions content dialog is empty on open, requiring a user to click next/previous problem.
We should fix this by showing a default one.
![image](https://github.com/storybuilder-org/StoryCAD/assets/49795711/0c601dee-5fd0-4426-a9ea-95bc52e04dc2)

**Comment by terrycox** [comment]
Closed per PR #586
