### ISSUE TITLE
Research new print dialog availability for windows 10.

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryCAD#583]
**Is your feature request related to a problem? Please describe.**
Windows 10 does not have access to the new print dialog due to a bug within windows.
This bug is apparently fixed with kb5005569.

If so the requirement to be running windows 11 for the new print menu should be removed.

**Comment by Rarisma** [comment]
Update
kb5005569 doesnt do what we think it did.
it appears that the print manager works on build 19045.

**Comment by Rarisma** [comment]
fixed in #604

**Comment by terrycox** [comment]
Closing per Jul 20 comment
