### ISSUE TITLE
"Empty Trash" disables banner bar method of creating new story element nodes.

### ISSUE THREAD

**Issue by SeanFager** [storybuilder-org/StoryCAD#596]
**Describe the bug**
If a user permanently deletes (a) story element(s) via the "empty trash" option of the "deleted story elements" entry in the navigation pane, the dropdown options for the "add/remove story elements" are removed except for the "Restore Story element" option [which does nothing]. 

**To Reproduce**
1. Create a new StoryCAD story.
2. Add an element.
3. Remove the element.
4. Via a right-click on the Deleted Story Elements 'rubbish bin' entry, Empty Trash.
5. Select the root node (Story Overview) in the navigation pane.
6. Select the "add/remove story elements" (+) from the banner.

**Expected behavior**
A dropdown list populates with the various story elements listed (and deletion/restoration options)

**Screenshots**
![image](https://github.com/storybuilder-org/StoryCAD/assets/120670213/4cbfcc12-6a3f-4950-a76e-d4a7bf7cedcd)
[NodeDrop.webm](https://github.com/storybuilder-org/StoryCAD/assets/120670213/5d000dd4-9bc5-4322-91d3-8adede6353c1)

**Additional context**
The method for adding a story element by rightclicking in the navigation pane still works after the trash is emptied, and restores the normal dropdown options for the banner's "add/remove story elements" menu entry.

Discovered in StoryCAD 2.11.0.0, OS Windows 11 ver 10.0.22621

**Comment by Rarisma** [comment]
Hello Sean,
This is not a bug per se.

StoryCAD tracks the last selected node within a variable, this variable is checked when you try to do spesific things in the app such as adding new nodes, which hides all new node options to prevent the user from adding new nodes to the trash.

This functionality can be seen within narrator view, which hides all node types except new sections.

Although this very report does make me realise that this system could be implemented better.
