### ISSUE TITLE
The images on our Store link are low-res and old

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryCAD#619]
**Describe the bug**
The images appear to be very low resolution and are fuzzy and difficult to read.
They also are old StoryBuilder images, not StoryCAD.
Also, it would be nice to see the new tree logo there.

**To Reproduce**
1. Go to ms-windows-store://pdp/?productid=9PLBNHZV1XM2
2. See error

**Expected behavior**
Decent-looking page. All users coming to download will see this, so it's imnportant.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Rarisma** [comment]
Images are updated for the 2.12, when we release it
