### ISSUE TITLE
Upgrade to WCT 8.0

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryCAD#634]
**Is your feature request related to a problem? Please describe.**
The Windows Community Toolkit has a new major release, 8.0. 

**Describe the solution you'd like**
Upgrade to it.
Examine for new features and breaking changes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Rarisma** [comment]
StoryCAD appears to have been on WCT 8.0 for some time now.
