### ISSUE TITLE
Invalid Syncfusion License

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryCAD#638]
**Describe the bug**
Testing the 2.12.0.0 Release build from 9/19/2023.
Upon opening a .stbx outline, you are presented with 'The included Syncfusion license key is invalid.' See attached screenshot.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Invalid Syncfusion License](https://github.com/storybuilder-org/StoryCAD/assets/5607778/f61a04ce-b5da-4f91-b153-4fca84be65cb)

**Additional context**

**Comment by Rarisma** [comment]
Fixed.
