### ISSUE TITLE
Fields delete free-text entries when dropdown viewed [2.12.0.0, untested elsewhere]

### ISSUE THREAD

**Issue by SeanFager** [storybuilder-org/StoryCAD#648]
**Describe the bug**
The "Problem Source" field (bottom of primary Problem page) accepts free text entries, but if the user activates the drop-down menu of prepared options and then clicks outside of the menu to collapse it, the free text entry is purged leaving the field blank.  Only appears to occur if the Problem is left and re-entered (or the Story closed and re-opened) between the entry of the free text and the accessing of the dropdown menu.

**To Reproduce**
1. Go to a Problem
2. Click on the Problem Source field and enter arbitrary text
3. Save the story, close it, re-open it.
4. Select the Problem Source dropdown chevron to review the built in options.
5. Click outside of the dropdown menu to collapse it.
6. Review the Problem Source field.  The data present before step 5 should still populate it, but as of this bug report does not.

**Expected behavior**
Free text Problem Source entries should be retained through dropdown navigation if no option is selected from the dropdown.

**Screenshots**
Error occurs 7 seconds into video.

https://github.com/storybuilder-org/StoryCAD/assets/120670213/33b113b3-2c04-423f-be90-1e04c7467a41

**Additional context**
Sample Story included a free text entry as distributed with the initial install, presumed to be an intentional feature.

**Comment by SeanFager** [comment]
UPDATE : Same issue occurs in every drop-down-but-allowing-for-free-text field that I've tested (Problems, Characters).  Does not purge entries previously chosen from drop-downs, only those manually entered.

**Comment by Rarisma** [comment]
This appears to be expected behavior within SyncFusion Comboboxes.
