### ISSUE TITLE
"Psychiatrist" appears twice in Role dropdown. [2.12.0.0]

### ISSUE THREAD

**Issue by SeanFager** [storybuilder-org/StoryCAD#651]
**Describe the bug**
The role of Psychiatrist appears twice (sequentially) in the dropdown.

**To Reproduce**
1. Go to a story
2. Navigate to a Character
3. On the Role subpage, select the Role field
4. Review the dropdown, which should have a single entry for each potential option.

**Expected behavior**
No duplicates.

**Screenshots**
![image](https://github.com/storybuilder-org/StoryCAD/assets/120670213/bb46a472-3352-4021-9335-4e7eee07795c)

**Comment by Rarisma** [comment]
Fixed in #652
